# Generated by Django 2.2.3 on 2019-07-10 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'All companies',
            },
        ),
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.Company')),
                ('taxonomy_package', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Client companies',
            },
            bases=('myapp.company',),
        ),
        migrations.CreateModel(
            name='SupplierCompany',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.Company')),
            ],
            options={
                'verbose_name_plural': 'Supplier companies',
            },
            bases=('myapp.company',),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
