# Generated by Django 2.2.3 on 2019-07-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ManyToManyField(to='myapp.Company'),
        ),
    ]
