# Generated by Django 2.2.4 on 2019-10-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190920_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualrapport',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
