# Generated by Django 2.2.4 on 2019-11-01 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_taxonomy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Company')),
            ],
        ),
        migrations.AlterModelOptions(
            name='taxonomy',
            options={'verbose_name_plural': 'Taxonomies'},
        ),
        migrations.DeleteModel(
            name='AnnualRapport',
        ),
        migrations.AddField(
            model_name='annualreport',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Taxonomy'),
        ),
    ]
