# Generated by Django 2.2.4 on 2019-11-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20191101_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='arelleCmdLine_options',
            field=models.TextField(default='--internetConnectivity=offline --packages "%ARELLE_HOME%/taxonomies/xbrl/www.xbrl.org.zip|%ARELLE_HOME%/taxonomies/eurofiling/www.eurofiling.info.zip|%ARELLE_HOME%/taxonomies/solvency/2.0.1/EIOPA_SolvencyII_XBRL_Taxonomy_2.0.1.zip|%ARELLE_HOME%/taxonomies/solvency/2.1.0/EIOPA_SolvencyII_XBRL_Taxonomy_2.1.0.zip|%ARELLE_HOME%/taxonomies/solvency/2.2.0/EIOPA_SolvencyII_XBRL_Taxonomy_2.2.0Hotfix.zip|%ARELLE_HOME%/taxonomies/solvency/2.3.0/EIOPA_SolvencyII_XBRL_Taxonomy_2.3.0_Hotfix.zip" --plugins="%ARELLE_HOME%/plugin/acsone/acsoneExtensions.py|%ARELLE_HOME%/plugin/validate/EBA"'),
            preserve_default=False,
        ),
    ]
